### ISSUE TITLE
Request API Change: Add registration_time for nse registration

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/api#115]
## Suggestion

Add `registration_time` for the network service endpoints.

```
message NetworkServiceEndpoint {
    string name = 1;
    repeated string network_service_names = 2;
    map<string, NetworkServiceLabels> network_service_labels = 3;
    string url = 4;
    google.protobuf.Timestamp expiration_time = 5;
    google.protobuf.Timestamp initial_registration_time = 6;
}

```

## How it will be used

`expiration_time` updates by registry by each refresh register.

`registration_time` will be set once per registration by the registry side.

`registration_time` can be used for statistics goals and also for identity issues and sorting issues.
 
## Motivation

1. Solves https://github.com/networkservicemesh/sdk/issues/1079
2. Solves  https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/3

**Comment by denis-tingaikin** [comment]
@edwarnicke WDYT?

**Comment by edwarnicke** [comment]
@denis-tingaikin Might it make more sense to call it initial_registration_time?

**Comment by denis-tingaikin** [comment]
@edwarnicke I think yes :) 

The description is updated.
