### ISSUE TITLE
Add field `groupId` to connectionContext

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/api#123]
## Description
Add new field `groupId` to `ConnectionContext` to enable possibility for mutually aware nse(which belongs to the same group)
```
message ConnectionContext {
    IPContext ip_context = 1; 
    DNSContext dns_context = 2; 
    EthernetContext ethernet_context = 3;
    map<string, string> extra_context = 4; 
    uint32 MTU = 5;
    string group_id =6 /*new field,*/
}
```

## Issue
part of https://github.com/networkservicemesh/api/issues/121

## Definition of done
- Add new field to proto file (it has to be at the bottom)
- Regenerate all code

**Comment by denis-tingaikin** [comment]
@Mixaster995 I don't think that adding id is a good idea. Could you please explain how it will be set on the NSE side?

**Comment by edwarnicke** [comment]
Can we close this issue?

**Comment by denis-tingaikin** [comment]
It's done.
