### ISSUE TITLE
Design and implement IPAM grpc service for vL3 cases

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/api#126]
## Overview

![image](https://user-images.githubusercontent.com/49399980/155163272-e7e7b071-62a8-4d89-9aa1-100e7f30896f.png)
## Link to the Google Docs document
https://docs.google.com/document/d/108QWsficn9adJrCppuHZcDi-AqlV7WFOaKKwYvIs-5k/edit?usp=sharing
( see at point 4.3)
## Service proto

```proto
service IPAMService {
  rpc Allocate(IPContext) returns (IPContext);
  rpc Free(IPContext) returns (google.protobuf.Empty);
}
```

[
](https://docs.google.com/document/d/108QWsficn9adJrCppuHZcDi-AqlV7WFOaKKwYvIs-5k/edit?usp=sharing)
## References

The alternative way for https://github.com/networkservicemesh/sdk/pull/1192

**Comment by denis-tingaikin** [comment]
> @denis-tingaikin Do we need to tie this to IPContext, or could it simply deal in prefixes?

Yes, I thought about this, so we also can go with

```proto
message IPAMServiceRequest {
   repeat string exclude_prefixes= 1;
}
message IPAMServiceResponse {
   string cidr = 1;
}
service ServiceName  {
   rpc Allocate (IPAMServiceRequest) returns (IPAMServiceResponse);
   rpc Free(IPAMServiceResponse) returns (google.protobuf.Empty);
}

```

**Comment by denis-tingaikin** [comment]
> @denis-tingaikin How are renewals handled? How are expirations handled?

I'll provide a **diagram of the interaction** as soon as we get API consent.

**Comment by denis-tingaikin** [comment]
> @denis-tingaikin Why is the NSC getting a /30 instead of a /32?

Thanks! Fixed.

**Comment by edwarnicke** [comment]
@denis-tingaikin Would it make sense to reflect the /32 assigned to the loopback interface for the VRF on VPP?

**Comment by denis-tingaikin** [comment]
Finally we with @edwarnicke  decided internally the next proto service

```proto
enum RequestType {
  UNDEFINED = 0;
  ALLOCATE = 1;
  DELETE = 2;
}

message IPAMRequest {
  string prefix = 2;
  repeated string exclude_prefixes =3;
}

message IPAMPrefix {
  RequestType type = 1;
  string prefix = 2;
}

service IPAMService  {
  rpc Request (IPAMRequest) returns (stream IPAMPrefix);
}
```

I've started to check corner cases for this service in the diagram of the interaction.

**Comment by denis-tingaikin** [comment]
Completed by https://github.com/networkservicemesh/api/pull/128
