### ISSUE TITLE
Make protocol and port parameters optional for policy based routing

### ISSUE THREAD

**Issue by szvincze** [networkservicemesh/api#127]
Currently `proto` and `port` fields of `PolicyRoute` struct are mandatory in `ConnectionContext`.

For this reason, if the user sets source port as `any` which means port range of 0-65535, then the whole range should be requested, which would end up quite a lot of policy routes.

Therefore these fields are expected to be optional.

If it implies change of the API, backward compatibility shall be considered.

**Comment by denis-tingaikin** [comment]
Probably am missing something... @szvincze Could you please clarify the use case and also how is ANY used in terms of vWire?

**Comment by edwarnicke** [comment]
@szvincze Normally I'd suggest treating the zero value as 'any' ... but it appears IP proto value of 0 is assigned to [IPv6 Hop By Hop Option](https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers).

[TCP/UDP port zero is reserved](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers).

Given that, how would you feel about interpreting a zero port as 'any'. 

For proto, would it make sense to its a little unclear how to proceed due to the unfortunate choice made of proto value 0 being assigned.  I feel like the default' behavior if you don't set anything in the rule should be 'ANY' ... but we can't do that *simply* with leaving proto value 0.  It feels like we may need some sort of bool to indicate that we should treat proto 0 as something other than ANY.

Thoughts?

**Comment by szvincze** [comment]
@edwarnicke, @denis-tingaikin Yes, we were thinking about similar kind of solution you described, with the additional bool.

**Comment by edwarnicke** [comment]
@szvincze Thoughts on naming of the bool?

**Comment by szvincze** [comment]
@edwarnicke Good question. First thought was `any_port_indicator`.

**Comment by edwarnicke** [comment]
@szvincze 

> @edwarnicke Good question. First thought was `any_port_indicator`.

I meant for the proto... for ports I think we are covered as port 0 is reserved (specifically so we can do things like interpret it as 'any' if we so choose).

**Comment by szvincze** [comment]
> I meant for the proto...
My fault. Of course, I wanted to write `any_proto_indicator`.

**Comment by edwarnicke** [comment]
@szvincze Sounds good :)

**Comment by LionelJouin** [comment]
Here are 2 proposals to solve the issue:
```
message PolicyRoute {
    string from  = 1;
    uint32 proto = 2;
    Range dest_port  = 3;
    repeated Route routes = 4;
}

message Range {
    uint32 start = 1;
    uint32 end = 2;
}
```
The user could let `dest_port` as `nil`, or he could add the range he wants using the new `range` message. If the user wants to have only 1 port in the policy, he could set `start` and `end` to the same value.
 
```
message PolicyRoute {
    string from  = 1;
    uint32 proto = 2;
    string dest_port  = 3;
    repeated Route routes = 4;
}
```
This is the one we discussed during the meeting. We would need to have a parser for the range.

We also have renamed the port property, so there will be no confusion between the destination and source (which could be extended later) port ranges. 

Here is where the implementation of the IP rules should be modified:
https://github.com/networkservicemesh/sdk-kernel/blob/2292537418c7c312ef8c2d0de2344e1f52040ef5/pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go#L102

**Comment by edwarnicke** [comment]
@tedlean This looks good to me API wise (other than a mild preference for dst_port rather than dest_port).  Is @ljkiraly about to pick up the implementation?

**Comment by tedlean** [comment]
yeah.. "dst_port" of course. 
I think it will be @LionelJouin that starts this task.

**Comment by LionelJouin** [comment]
Sure thank you

**Comment by edwarnicke** [comment]
@LionelJouin One quick pointer, I think you will find the bulk of the germane code here: https://github.com/networkservicemesh/sdk-kernel/tree/main/pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule
