### ISSUE TITLE
Some of helper functions are wrong and some of them are not using

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/api#143]
We need to recheck all helper functions in api and probabbly cover them by unut tests.

Some of helper functions are wrong.

1. See at https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/ipcontext_helpers.go#L192 //Note: this makes ipNet incorrect

2. This is not using https://github.com/networkservicemesh/api/blob/ad449d9a91927d5206ebfad5c6d81f23af0f28bb/pkg/api/networkservice/connection_helpers.go#L37 and its wrong

3. This is not using https://github.com/networkservicemesh/api/blob/ad449d9a91927d5206ebfad5c6d81f23af0f28bb/pkg/api/networkservice/connection_helpers.go#L48 and its wrong

## Solution

1. Cleanup helpers
2. (?) Add unit tests

**Comment by denis-tingaikin** [comment]
@edwarnicke Can we schedule this for v1.5.0?

**Comment by NikitaSkrynnik** [comment]
Seems like done: https://github.com/networkservicemesh/api/pull/152
