### ISSUE TITLE
Spec: Store spiffeID of NSE in NetworkSerivceEndpoint message

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/api#148]
## Description
Current implementation of authorization for registry may be insecure when registry restarts.

## Current behavior
When NSE goes to registry to register itself, registry stores it's spiffeID in a map. Registry uses this map to check that different spiffeIDs don't register NSEs with the same names. When registry restarts, the map is removed, and bad NSE has a possibility to register itself under the name of a good NSE.

## Solution
- We can use gRPC metadata to transfer `path`, which is private and constracted during Registeration of Endpoint. Authorize chain element can get private `path` from gRPC medatada and check policies. 
- We can store spiffeID in NSE entry in etcd. When a bad NSE tries to register itself as a good NSE, we can get entry from etcd and check that spiffeID of a good one is equal to spiffeID of a bad one. If spiffeIDs are different, registry won't allow bad NSE to register. It would work even if registry restarted, because spiffeID of good NSE is stored in etcd. (Options for how we can store spiffe id are listed below)

## Options
We can store additional information in NSE CRD that can be helpful for future authorization cases. Also we can use NSE labels to store spiffeID. 

### Option 1: Store only NSE spiffeID in NSE CRD
Fixes registry security issue.
```proto
message NetworkServiceEndpoint {
    string name = 1;
    repeated string network_service_names = 2;
    map<string, NetworkServiceLabels> network_service_labels = 3;
    string url = 4;
    string id = 5;
    google.protobuf.Timestamp expiration_time = 6;
    google.protobuf.Timestamp initial_registration_time = 7;
}
```

### Option 2: Store a list of spiffeIDs in NSE CRD from the path that was constructed during initial NSE registration
Fixes registry security issue. It may be useful for authorization cases that we haven't considered yet
```proto
message NetworkServiceEndpoint {
    string name = 1;
    repeated string network_service_names = 2;
    map<string, NetworkServiceLabels> network_service_labels = 3;
    string url = 4;
    repeated string path_ids = 5;
    google.protobuf.Timestamp expiration_time = 6;
    google.protobuf.Timestamp initial_registration_time = 7;
}
```
### Option 3: Store spiffeID of NSE in NSE labels.
Fixes registry sequrity issue. Doesn't require any changes in API
```go
nse := &registryapi.NetworkServiceEndpoint{
		Name: "nse",
		NetworkServiceLabels: map[string]*registryapi.NetworkServiceLabels{
			"networkservice": {
				Labels: map[string]string{
					"id": "spiffe://test.com/nse",
				},
			},
		},
		NetworkServiceNames: []string{"networkservice"},
	}
```

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik Could you also add proto examples to get options easy?

```proto
# TODO
```

**Comment by NikitaSkrynnik** [comment]
## cmd repositories PRs

- https://github.com/networkservicemesh/cmd-registry-proxy-dns/pull/547
- https://github.com/networkservicemesh/cmd-nse-remote-vlan/pull/118
- https://github.com/networkservicemesh/cmd-nse-vfio/pull/407
- https://github.com/networkservicemesh/cmd-nsc-simple-docker/pull/44
- https://github.com/networkservicemesh/cmd-nse-supplier-k8s/pull/231
- https://github.com/networkservicemesh/cmd-nse-l7-proxy/pull/61
- https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/pull/64
- https://github.com/networkservicemesh/cmd-nse-vl3-vpp/pull/138
- https://github.com/networkservicemesh/cmd-nse-firewall-vpp/pull/323
- https://github.com/networkservicemesh/cmd-nse-icmp-responder-vpp/pull/492
- https://github.com/networkservicemesh/cmd-nse-vlan-vpp/pull/235
- https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/756
- https://github.com/networkservicemesh/cmd-forwarder-sriov/pull/544
- https://github.com/networkservicemesh/cmd-forwarder-ovs/pull/198
- https://github.com/networkservicemesh/cmd-nsmgr/pull/560

**Comment by denis-tingaikin** [comment]
Seems like completed by https://github.com/networkservicemesh/api/issues/148#issuecomment-1338905268

@NikitaSkrynnik Thanks!
