### ISSUE TITLE
Spec: Select the remote mechanism

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/api#149]
## Intro

Currently, we have two remote mechanisms: VXLAN (**Ethernet**) and Wireguard (**IP**).

The selection for those mechanisms is working fine because they have a diff by **Payload**.

What NSM should do if we will have a few IP mechanisms or a few Ethernet mechanisms?

## Problems

1. How to select a remote mech for a pair nsc/nse?
2. How to select a remote mech for a couple of pairs nsc/nse?
3.  How to select a remote mech for a composition of nse?
4.  How to select a remote mech for a couple of compositions of nse?

## Solutions

1. Extend match metadata 
2. Your options

**Comment by glazychev-art** [comment]
## Solution - Extend match metadata

1. Add to `registry.NetworkService.Matches.Metadata` ([link](https://github.com/networkservicemesh/api/blob/main/pkg/api/registry/registry.proto#L22-L24)) a new `map<string, string> filterMechanisms`, where _key_ - `mechanism.Cls` ("LOCAL" or "REMOTE"), _value_ - array of allowed mechanisms (separated by ','). Allow all mechanisms if _value_ is empty.
2. Improve [discover](https://github.com/networkservicemesh/sdk/tree/main/pkg/networkservice/common/discover) to store and handle information about which Endpoint corresponds to which Match.
3. [selectEndpointServer](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/roundrobin/server.go) adds to `context.Metadata` a mechanism that can be taken from Match.Metadata.FilterMechanisms.
4. [filterMechanismsClient](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/filtermechanisms/client.go) takes mechanism from `context.Metadata` and filters `MechanismPreferences` (alongside cls.LOCAL/REMOTE). 

After that, only the desired mechanism should remain in the preferences.

**Comment by glazychev-art** [comment]
@edwarnicke 
Any thoughts?

**Comment by glazychev-art** [comment]
I think we can close this issue because we found another solution here - https://github.com/networkservicemesh/sdk-vpp/issues/638
