### ISSUE TITLE
MatchesMonitorScopeSelector helper function checks only one field

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/api#164]
## Description 
[MatchesMonitorScopeSelector](https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/connection_helpers.go#L128-L161) function takes into account only PathSegment.Name - https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/connection_helpers.go#L150

This is wrong, because there are other fields in the PathSegment - at least we use connection ID in some places:
https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/heal/eventloop.go#L60-L65
https://github.com/networkservicemesh/cmd-nsc/blob/main/main.go#L253-L256

**Comment by denis-tingaikin** [comment]
Seems like done.

@glazychev-art , @NikitaSkrynnik  Thanks!
