### ISSUE TITLE
Add to networkservices and networkserviceendpoints status enum

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/api#81]
## Description

status field can be super useful for watching systems (Find(Watch=true)). 
This can show that NSE/NS running or terminating and so on.

The field can be also used for heal scenarios.

## Implemetation

Add into networkservices and networkserviceendpoints status enum with next states:

```go
type Status uint32
const Unknown Status = 0
const Running Status = 1
const Terminating Status = 2
```

**Comment by edwarnicke** [comment]
How long do we expect termination to take?

Could you describe a bit more about how you expect this to work?

**Comment by denis-tingaikin** [comment]
How long do we expect termination to take?

In my mind Status.Terminating sets only on Uregister and sends as an event for all listeners.

**Comment by edwarnicke** [comment]
OK... that makes sense... so what do you expect the Listeners to do on Status.Terminating?

**Comment by denis-tingaikin** [comment]
@edwarnicke For example re-register networkservice.  Currently, network services deleting when all NSEs that using this dying.
So Endpoint could listen to its NS registry and in case of NSE registry died it can re-register NetworkService. In short, it can be used in healing scenarios.

**Comment by edwarnicke** [comment]
@denis-tingaikin Couldn't the NSE simply listen to the Registry to see if its NSE entry in the registry disappeared reregister?  I don't see how a Terminating Status makes for a better way to do that, given that the NSE is the one setting its state to 'Terminating' ... or am I missing something?

**Comment by denis-tingaikin** [comment]
@edwarnicke  

> Couldn't the NSE simply listen to the Registry to see if its NSE entry in the registry disappeared reregister?

Yes, it is a problem.  

For example:

Currently, we can detect that NSE is deleted by  `watch`. (We can receive an event with NSE.ExpirationTime < 0)
**But we can detect that NS is deleted.** 

For a user application that is using NS Server AOU is super difficult to track that NS is deleted.

Also criteria `NSE.ExpirationTime < 0` maybe is not clear for users.

So these problems can be solved by Status enum :)

**Comment by edwarnicke** [comment]
Just to make sure I understand

1. it sounds like the NS does not have an expiration time, and thus you cannot tell its being *deleted* based on ```NSE.ExpirationTime < 0```, correct?
2. ```NSE.ExpirationTime < 0``` is a little less than clear to users wrt deletion for NSEs.

Are those the two points?  Did I miss any?

**Comment by denis-tingaikin** [comment]
@edwarnicke Yes, it is correct points :)

**Comment by edwarnicke** [comment]
@denis-tingaikin Lets talk through this a bit first.

1. How do we decide an NS is in Terminating status?
2. Which entities do what in response to the NS being in Terminating status?
3. How do we decide and NSE is in Terminating status?
4. Which entities do what in response to the NSE being in Terminating status?

And the same questions for Running state

Also: how does an entity enter and leave Unknown status?

I guess the question is: what is the state machine of the states?

**Comment by denis-tingaikin** [comment]
## Terminating

> 1. How do we decide an NS is in Terminating status? 

We can send the update with this status on NS deleting

> 2. Which entities do what in response to the NS being in Terminating status?

The endpoint could listen to events on this and do re-register for its NSs

> 3. How do we decide and NSE is in Terminating status?

We can send the update with this status on NSE deleting

> 4. Which entities do what in response to the NSE being in Terminating status?

All current staff stat watching for NSE. ExpirationTime < 1

## Running

> 1. How do we decide an NS is in Terminating status? 

We can send the update with this status on NS added/updated in the registry

> 2. Which entities do what in response to the NS being in Running status?

We'll do the same staff that we currently doing for NSs which NSEs have not ExpirationTime < 0

> 3. How do we decide and NSE is in Terminating status?

We can send the update with this status on NS added/updated in the registry

> 4. Which entities do what in response to the NSE being in Running status?

We can do the same staff that we currently doing for NSEs that have not ExpirationTime < 0

## Unknown status

> Also: how does an entity enter and leave Unknown status?

Unknown status is the default value for NSE, NS on being registered. So it means that NSE is not registered yet.

**Comment by edwarnicke** [comment]
So it sounds like mostly we are simply communicating the fact that an event is a 'delete' even using the status field.  While I strongly agree with you that the 'zero' value for a status should be UNKNOWN, it seems that every registration would involve a Running Status and deletion would involve a Delete status.

It sort of feels like we are using Status to make up for the lack of 'event' wrappers for registration.

**Comment by denis-tingaikin** [comment]
> It sort of feels like we are using Status to make up for the lack of 'event' wrappers for registration.

Yes you are correct, as an alternative, we can consider wrapping NSE/NS for find API

**Comment by edwarnicke** [comment]
Do question: if all we are communicating is 'this is deleted'.  Could this be signaled with a simple deleted bool?

**Comment by denis-tingaikin** [comment]
> Do question: if all we are communicating is 'this is deleted'. Could this be signaled with a simple deleted bool?

My thoughts on this:

1. This solves this issue.
2. This prevents potential API leaks, that we can face if we go with statuses.

But I worry that actually info about deleting is needed only for Find API cases. What do you think about modifying only find API?

For example we could try to modify [Queries](https://github.com/networkservicemesh/api/blob/master/pkg/api/registry/registry.proto#L49-L56) and do something like this:

```go
message NetworkServiceQuery {
    NetworkService network_service = 1;
    bool watch = 2;
    bool deleted = 3;
}
```

**Comment by edwarnicke** [comment]
> Or add a response on queries:
> 
> ```go
> message NetworkServiceResponse {
>     NetworkService network_service = 1;
>     bool deleted = 2;
> }
> ```
I like this option a lot better :)

**Comment by denis-tingaikin** [comment]
@edwarnicke PRs are merged. Closing this.
